### ISSUE TITLE
How to push from wiki to website

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/RequestPolicyContinued.github.io#12]
@nodiscc what are the steps needed to push from the wiki to the website? Is it the same repository with multiple "remotes"?

Is the following correct?

```
$ git remote
wiki
website
$ git pull wiki
$ ./build.sh
$ git push website master:master
```

**Comment by nodiscc** [comment]
@myrdd this is right. Just review the changes after pulling from the wiki (it's world writable)

**Comment by myrdd** [comment]
okay
