### ISSUE TITLE
How to update the wiki

### ISSUE THREAD

**Issue by DJ-Leith** [RequestPolicyContinued/RequestPolicyContinued.github.io#14]
Quoted from
**the project's website**
https://github.com/RequestPolicyContinued/requestpolicy/issues/445

On 2015-06-23 @nodiscc wrote in this [comment](https://github.com/RequestPolicyContinued/requestpolicy/issues/445#issuecomment-114584341)

> The new website/wiki is live at https://requestpolicycontinued.github.io/ 
> and https://github.com/RequestPolicyContinued/requestpolicy/wiki

snip

> Please review, report and fix any problem you may find.

@myrdd said:

> wow @nodiscc great! Thank you for your effort!

I agree, it is very good.

I have now read all of the **website** https://requestpolicycontinued.github.io/
and all of the **wiki** https://github.com/RequestPolicyContinued/requestpolicy/wiki

At the moment, the 'meaning of the words' are very similar.
The 'looks' are slightly different: the **website** looks a little better than the **wiki**
but the wiki is 'quite presentable' (I mean easy to read).

I particularly like the screenshots in the **Quickstart**

Website: https://requestpolicycontinued.github.io/Quickstart.html
Wiki: https://github.com/RequestPolicyContinued/requestpolicy/wiki/Quickstart

The **Quickstart** is much better than it was on 2015-06-22.

The links in the _wiki_ are generally working but there are still some broken links in the _website_.
There are, at the moment, 13 pages in the wiki.

I also see that there are **issues** for the website/wiki:

https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io/issues

@nodiscc and @myrdd, I think you know all of the above but I wanted to make sure
all readers understood my current understanding, my 'starting position'.

If I understand correctly, one way to think of the website/wiki is:
'the wiki is a preview of the website'.  Changes are made in the wiki and are pushed to the website.

I am now going to ask some questions in the spirit of 'how can we make this even better'.

**_1.**_
Would you like a **separate** wiki?

Another option would be to have a website (that is carefully updated) and a **separate** wiki. 
The **wiki** could have more input from the community
but which would NOT be 'pushed to the official website'.

Potential advantages include:
- more contributions from the community (from 'non programers').
- changes in the wiki will not 'damage the website' (see **2** - below) for an example.
- the wiki navigation is already working.
- easy to add screenshots (to an issue) which can then be used in the wiki.

---

**_2.**_
How best to update the wiki.

In theory there are several options:

**2.1** Have a discussion issue for 'new pages' or 'big changes'.

**2.2** In addition to **2.1** have specific issues
(like we have for **Pages need a header with a back button** #2 and
**main, quickstart: dead 'subscriptions' links** #8). 

**2.3** Do a <code>git checkout</code> as described by  @nodiscc [here](https://github.com/RequestPolicyContinued/requestpolicy/issues/445#issuecomment-114694717)
and in
**How to push from wiki to website** #12 

**2.4** Edit the wiki.

I would be happy with _your_ choice.

However, I don't think I would contribute to **2.3** Do a <code>git checkout</code>.

On 2015-06-24 I did think about this.
Rather than 'write a long post' I decided to make a very small change, that was easy to
'see and reverse' using method **2.4. Edit the wiki** (but without doing a <code>git checkout</code>).
See: https://github.com/RequestPolicyContinued/requestpolicy/wiki/Security/_history

At the time, and on 2015-06-25, I think this 'worked OK'.
The "... described above" became "... described below" in the wiki and, IIRC, on the website.
The website did look like the wiki with a 'hot link' for "Cross-Site Request Forgery", IIRC.

Today, 2015-06-27, the 'wiki is still OK' see
https://github.com/RequestPolicyContinued/requestpolicy/wiki/Security

but the 'website has markdown' see
https://requestpolicycontinued.github.io/Security.html
See this markdown:
<code> [Cross-Site Request Forgery] </code>.

So, this might be 'just teething trouble'
but I am keen help and very keen to avoid giving you extra work.

I have opened a separate issue (#15) for the specific case of the <code>Security.html</code>
that is now 'messed up'.

I have noticed several areas in the wiki, and some comments in
**the project's website**
https://github.com/RequestPolicyContinued/requestpolicy/issues/445
where I think it would good to 'make things even better'.

I'll wait for feedback and guidance from @nodiscc and @myrdd
on the 'best way forward'.

**Comment by nodiscc** [comment]
The normal workflow for the wiki is
- let users/everyone update the wiki
- at some random interval, review the changes made to the wiki, fix things if needed, rebuild HTML pages from markdown and upload to the website repo.

The main benefit is not having to maintain 2 separate documentation sets.

You are right, raw markdown appears on Security.html, thanks for reporting it at https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io/issues/15. I should have reviewed the changes better.

I am not sure this needs more discussion; I hope the above workflow clarifies things. Closing but feel free to add comments.

Edit: if you think some docs belong on the wiki but _not_ on the website, we could make the website a separate branch.

**Comment by myrdd** [comment]
> Edit: if you think some docs belong on the wiki but not on the website, we could make the website a separate branch.

or we exclude them via the site configuration: http://jekyllrb.com/docs/configuration/#global-configuration
I suggest to exclude e.g. `*.md`
