### ISSUE TITLE
Raw markdown showing on Security.html

### ISSUE THREAD

**Issue by DJ-Leith** [RequestPolicyContinued/RequestPolicyContinued.github.io#15]
@nodiscc, I am sorry for the extra work.

Copied from **How to update the wiki** #14

On 2015-06-24 I did think about this.
Rather than 'write a long post' I decided to make a very small change, that was easy to
'see and reverse' using method **2.4 Edit the wiki** (but without doing a <code>git checkout</code>).
See: https://github.com/RequestPolicyContinued/requestpolicy/wiki/Security/_history

At the time, and on 2015-06-25, I think this 'worked OK'.
The "... described above" became "... described below" in the wiki and, IIRC, on the website.
The website did look like the wiki with a 'hot link' for "Cross-Site Request Forgery", IIRC.

Today, 2015-06-27, the 'wiki is still OK' see
https://github.com/RequestPolicyContinued/requestpolicy/wiki/Security

but the 'website has markdown' see
https://requestpolicycontinued.github.io/Security.html
See this markdown:
<code> [Cross-Site Request Forgery] </code>.

So, this might be 'just teething trouble'
but I am keen help and very keen to **avoid giving you extra work**.

Please can you fix this and advise, in #14, about how to avoid
'edits in the wiki damage the website'.

**Comment by nodiscc** [comment]
You are right, raw markdown appears on Security.html, thanks for reporting it. I should have reviewed the changes better.
