### ISSUE TITLE
Website Navigation

### ISSUE THREAD

**Issue by DJ-Leith** [RequestPolicyContinued/RequestPolicyContinued.github.io#17]
Quoted from #14

> I have now read all of the **website** https://requestpolicycontinued.github.io/
> and all of the **wiki** https://github.com/RequestPolicyContinued/requestpolicy/wiki
> 
> At the moment, the 'meaning of the words' are very similar.
> The 'looks' are slightly different: the **website** looks a little better than the **wiki**
> but the wiki is 'quite presentable' (I mean easy to read).

snip

> If I understand correctly, one way to think of the website/wiki is:
> 'the wiki is a preview of the website'. Changes are made in the wiki and are pushed to the website.

@nodiscc said:

> The normal workflow for the wiki is
> - let users/everyone update the wiki
> - at some random interval, review the changes made to the wiki, fix things if needed, rebuild HTML pages from markdown and upload to the website repo.
> 
> The main benefit is not having to maintain 2 separate documentation sets.

An important difference, between the website and the wiki, is navigation.

On the wiki there are 13 pages.  These can all be reached via the 'links in the frame at the top right' of every page in the wiki.

On the website there are some 'unreachable pages'.  There is no link **in the pages** that 'goes to the unreachable page'.
For example, AFAICT, there is no link to "What-is-prefetching".

I expect the link to be: 
https://requestpolicycontinued.github.io/What-is-prefetching.html
The page does exist - good.

While there are less than 20 pages I think the website might not need 'navigation'
but if there was a 'back to Home' link on each page it would be easier to use.

Some wikis have many pages.
For example
https://github.com/gorhill/uBlock/wiki
has 84 pages (at 2015-07-02) and it had a Home page that is like a 'Table of Contents'.

Some pages have "Back to Wiki home" link (at the top),
and there is a "Wiki home" link in the top right of **every** page.

**Comment by nodiscc** [comment]
> if there was a 'back to Home' link on each page it would be easier to use.

https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io/issues/2

>  For example, AFAICT, there is no link to "What-is-prefetching".

Yes there is one in the FAQ

https://github.com/RequestPolicyContinued/RequestPolicyContinued.github.io/search?utf8=%E2%9C%93&q=What-is-prefetching.html
