### ISSUE TITLE
Pages need a header with a back button

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/RequestPolicyContinued.github.io#2]
eg. when on https://requestpolicycontinued.github.io/Contributing.html you have to use the browser back button to get back to the home page. The page should offer a link for this basic functionality.

**Comment by DJ-Leith** [comment]
Quoted from #14

> I have now read all of the **website** https://requestpolicycontinued.github.io/
> and all of the **wiki** https://github.com/RequestPolicyContinued/requestpolicy/wiki
> 
> At the moment, the 'meaning of the words' are very similar.
> The 'looks' are slightly different: the **website** looks a little better than the **wiki**
> but the wiki is 'quite presentable' (I mean easy to read).

snip

> If I understand correctly, one way to think of the website/wiki is:
> 'the wiki is a preview of the website'. Changes are made in the wiki and are pushed to the website.

@nodiscc said:

> The normal workflow for the wiki is
> - let users/everyone update the wiki
> - at some random interval, review the changes made to the wiki, fix things if needed, rebuild HTML pages from markdown and upload to the website repo.
> 
> The main benefit is not having to maintain 2 separate documentation sets.

An important difference, between the website and the wiki, is navigation - see #17.

Assuming that the website will not have any special navigation.

Can I suggest a 'Back Button' or link that goes 'Home'.
I recommend that every page (except the Home page) has one at the top.
In long pages have 'link to Home' at the bottom of the page (in addition to the one at the top).

Home, on the wiki, is  https://github.com/RequestPolicyContinued/requestpolicy/wiki
Home, on the website, is https://requestpolicycontinued.github.io/

**Comment by myrdd** [comment]
Yes, a back button would improve page navigation. I also think an automatically generated "sitemap" could be helpful. However, the wiki already contains such a sitemap, so I won't create an issue for now.
