### ISSUE TITLE
rename `flag-tiny.png`

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/RequestPolicyContinued.github.io#21]
`flag-tiny.png` is in fact 32px big, so not tiny. Let's rename it to `flag-32px.png`.

If you want, we can also rename `flag.png` to `flag-16px.png`.

**Comment by nodiscc** [comment]
Sorry for the late reply @myrdd of course feel free to change the file names

> rename it to flag-32px.png
> rename flag.png to flag-16px.png

This makes sense
