### ISSUE TITLE
replace.sed and .html file extensions

### ISSUE THREAD

**Issue by myrdd** [RequestPolicyContinued/RequestPolicyContinued.github.io#22]
I was looking for a shorter form of the `sed` replace lines in `replace.sed`:

```
s/](About)/](About.html)/g
s/](FAQ)/](FAQ.html)/g
…
```

By the way it doesn't allow links containing a `#` hash tag. I came up with the following one-liner, which requires sed's `--regexp-extended` option:

``` sed
s_\]\(([-a-zA-Z]+)(\#[^)]+)?\)_](\1.html\2)_g
```

The line looks kinda ugly, but it works. But then I recognized that on Github Pages the files can be accessed _without_ the `.html` ending at all. Both links work:
- https://requestpolicycontinued.github.io/FAQ
- https://requestpolicycontinued.github.io/FAQ.html

This means we could skip the `sed` line completely – but IMHO we should keep adding the `.html` extension. So @nodiscc what do you think about the one-liner? I can create a pull request.

**Comment by nodiscc** [comment]
> By the way it doesn't allow links containing a # hash tag
> I came up with the following one-liner

This is much better, thank you. Nice regex.

> on Github Pages the files can be accessed without the .html ending at all
> we could skip the sed line completely – but IMHO we should keep adding the .html extension.

Yes. Nice find and related to #10 because testing locally would have spotted this.
