### ISSUE TITLE
How to track whitelists with version control?

### ISSUE THREAD

**Issue by mk-pmb** [RequestPolicyContinued/RequestPolicyContinued.github.io#26]
Hello, thank you for continuing development of RequestPolicy!

One major difference I have observed is that the new edition stores its whitelists in enormous strings inside `prefs.js`. Are there alternatives that produce more meaningful diffs for tracking Firefox config with version control software?

If not, could someone add a feature to auto-import `[profile]/RequestPolicy/*.wls` (or similar) as whitelists, and when saving to `prefs.js`, to only store those entries that aren't in any of the auto-import whitelists yet?

PS: Sorry if this was the wrong repo for this issue. I'll gladly repost it to the "requestpolicy" repo if that's more appropriate.

**Comment by myrdd** [comment]
Hi @mk-pmb, thanks for your suggestion. Please check out issue https://github.com/RequestPolicyContinued/requestpolicy/issues/339. If it is what you want, give it a "+1". Otherwise, please create a new issue on the "requestpolicy" repo, suggesting your alternative approach.

> PS: Sorry if this was the wrong repo for this issue. I'll gladly repost it to the "requestpolicy" repo if that's more appropriate.

Yes, it's the wrong repo. This is about subscription rules only ;)

**Comment by mk-pmb** [comment]
Now that I managed to get the really latest version (1.0.beta11pre3 this time), subscriptions sound like they could be the way to go. I use that approach for AdBlock Plus already, provide the versioned rules as subscriptions and arrange to be warned whenever I'd try and commit a profile update with manual rules.

I hope you can help me decide again, whether I need to look harder in the docs or file a feature request on the other repo: Where do I add the URLs for my custom subscriptions? In the settings' "Subscription Policies" panel, I can only find checkboxes and a "Learn more" link, which seems to exclusively cover "official" subscriptions.

**Comment by myrdd** [comment]
> Where do I add the URLs for my custom subscriptions? In the settings' "Subscription Policies" panel, I can only find checkboxes and a "Learn more" link, which seems to exclusively cover "official" subscriptions.

I'm sorry, RequestPolicy doesn't have an option to add custom subscription URLs yet, but it's planned. Please follow https://github.com/RequestPolicyContinued/requestpolicy/issues/736

**Comment by mk-pmb** [comment]
Will do, thanks!

**Comment by mk-pmb** [comment]
Since RP can't currently read multiple user-provided config files, I resorted to having my `user.json` be generated. In case someone else wants to go this route, feel free to try my [generator script](https://github.com/mk-pmb/firefox-requestpolicy-util).

**Comment by myrdd** [comment]
Nice! Feel free to just put that comment also on https://github.com/RequestPolicyContinued/requestpolicy/issues/736, people will more likely find your script there.

**Comment by mk-pmb** [comment]
Thanks! I'll take that as a maintainer's recommendation, which thereby solves this issue for the time being. As I see, @nodiscc already added the hint in the other thread, so all is settled.
