### ISSUE TITLE
Pages have no <title>

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/RequestPolicyContinued.github.io#3]
```
man pandoc

 -T STRING, --title-prefix=STRING
              Specify STRING as a prefix at the beginning of  the  title  that
              appears  in  the HTML header (but not in the title as it appears
              at the beginning of the HTML body).  Implies --standalone.
```

**Comment by myrdd** [comment]
The template currently is as follows.

``` html
<title>$if(title-prefix)$$title-prefix$ - $endif$$pagetitle$</title>
```

Our own template could be:

``` html
<title>$if(pagetitle)$$pagetitle$ - $endif$RequestPolicy Continued</title>
```

Then the `pandoc` command will have the option `--from markdown_github+pandoc_title_block` and on the markdown pages we'll have `% {title}`, e.g. `% FAQ`.

**Comment by nodiscc** [comment]
Copied from #20

---

Thanks for the PR. Looks good enough to merge, but I suggest to create a custom [template](http://pandoc.org/README.html#templates), and the [`pandoc_title_block`](http://pandoc.org/demo/example9/pandocs-markdown.html#extension-pandoc_title_block) extension.
- With the `pandoc_title_block` extension…
  - there's no additional `-` minus sign in the `<title>`
  - we don't need the `<!-- … -->` comments and its parsing
- With the template…
  - we can create a `<title>` _suffix_, that is, `- RequestPolicy Continued`.
  - we can remove the `<h1>` created by the `pandoc_title_block` extension
  - it's easy to add a custom header, issue #2. In fact, we could even put the main page's header into the template, removing the need of html code in `Home.md`.
  - we can also add the License footer

---

Implementation notes for the **custom header** (#2):
1. set a variable called „home“, using `--variable`
2. check for the `home` variable:

```
$if(home)$
<!-- home header -->
$else$
<!-- non-home header with back button -->
$endif$
```
