### ISSUE TITLE
Restore missing Unit tests section

### ISSUE THREAD

**Issue by nodiscc** [RequestPolicyContinued/RequestPolicyContinued.github.io#6]
https://github.com/RequestPolicyContinued/requestpolicy/issues/445#issuecomment-114683363

**Comment by myrdd** [comment]
Any chance to find the commit(s)?

**Comment by nodiscc** [comment]
I'm so damn sorry... I can't find the commit back.
https://gist.github.com/nodiscc/baee950aff4e6d945558
I've tried the reflog and `grep -r marionette ~/`, looked for older copies of the repo...
I won't do it again.
Maybe someone has a copy of the previous history?

**Comment by myrdd** [comment]
> https://gist.github.com/nodiscc/baee950aff4e6d945558

Heh, you made me smile. It's a good point. Thank you for searching. Don't be too worried, it wasn't that big work.

P.S.: You might add the `-ai` options to `grep` if you're looking hard for something.
